//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDayDisplayApp.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaceDayDisplayApp.App_GlobalResources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ErrorMessage_RegistrationPage_ConfirmPassword_Compare {
            get {
                return ResourceManager.GetString("ErrorMessage_RegistrationPage_ConfirmPassword_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ErrorMessage_RegistrationPage_Email_StringLength {
            get {
                return ResourceManager.GetString("ErrorMessage_RegistrationPage_Email_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ErrorMessage_RegistrationPage_Password_StringLength {
            get {
                return ResourceManager.GetString("ErrorMessage_RegistrationPage_Password_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Label_RegistrationPage_ConfirmPasswordDisplayName {
            get {
                return ResourceManager.GetString("Label_RegistrationPage_ConfirmPasswordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary countries of interest.
        /// </summary>
        public static string Label_RegistrationPage_CountriesDisplayName {
            get {
                return ResourceManager.GetString("Label_RegistrationPage_CountriesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Label_RegistrationPage_EmailDisplayName {
            get {
                return ResourceManager.GetString("Label_RegistrationPage_EmailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No to newsletter.
        /// </summary>
        public static string Label_RegistrationPage_NoToNewsletterDisplayName {
            get {
                return ResourceManager.GetString("Label_RegistrationPage_NoToNewsletterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_RegistrationPage_PasswordDisplayName {
            get {
                return ResourceManager.GetString("Label_RegistrationPage_PasswordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select preferred language.
        /// </summary>
        public static string Label_RegistrationPage_SelectLanguageDisplayName {
            get {
                return ResourceManager.GetString("Label_RegistrationPage_SelectLanguageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind of intelligence are you looking for specifically?.
        /// </summary>
        public static string Label_RegistrationPage_SignUpCommentDisplayName {
            get {
                return ResourceManager.GetString("Label_RegistrationPage_SignUpCommentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Label_RegistrationPage_UsernameDisplayName {
            get {
                return ResourceManager.GetString("Label_RegistrationPage_UsernameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact support..
        /// </summary>
        public static string Text_ConfirmationFailure_Page {
            get {
                return ResourceManager.GetString("Text_ConfirmationFailure_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation failed.
        /// </summary>
        public static string Title_ConfirmationFailure_Page {
            get {
                return ResourceManager.GetString("Title_ConfirmationFailure_Page", resourceCulture);
            }
        }
    }
}
