//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDayDisplayApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Gear = new HashSet<Gear>();
            this.Going = new HashSet<Going>();
            this.Horse = new HashSet<Horse>();
            this.Jockey = new HashSet<Jockey>();
            this.Jockey1 = new HashSet<Jockey>();
            this.Meeting = new HashSet<Meeting>();
            this.RaceCity = new HashSet<RaceCity>();
            this.RaceCourse = new HashSet<RaceCourse>();
            this.RaceType = new HashSet<RaceType>();
            this.Settings = new HashSet<Settings>();
            this.Sex = new HashSet<Sex>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<bool> inUse { get; set; }
        public Nullable<bool> usesMetric { get; set; }
        public byte[] Flag { get; set; }
        public Nullable<System.DateTime> SeasonStart { get; set; }
    
        public virtual ICollection<Gear> Gear { get; set; }
        public virtual ICollection<Going> Going { get; set; }
        public virtual ICollection<Horse> Horse { get; set; }
        public virtual ICollection<Jockey> Jockey { get; set; }
        public virtual ICollection<Jockey> Jockey1 { get; set; }
        public virtual ICollection<Meeting> Meeting { get; set; }
        public virtual ICollection<RaceCity> RaceCity { get; set; }
        public virtual ICollection<RaceCourse> RaceCourse { get; set; }
        public virtual ICollection<RaceType> RaceType { get; set; }
        public virtual ICollection<Settings> Settings { get; set; }
        public virtual ICollection<Sex> Sex { get; set; }
    }
}
