//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDayDisplayApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseVariant
    {
        public CourseVariant()
        {
            this.Meeting = new HashSet<Meeting>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> RaceCourseId { get; set; }
        public Nullable<short> LengthHomeStraightm { get; set; }
        public Nullable<short> Circumferencem { get; set; }
    
        public virtual RaceCourse RaceCourse { get; set; }
        public virtual ICollection<Meeting> Meeting { get; set; }
    }
}
