//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDayDisplayApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distance
    {
        public Distance()
        {
            this.Race = new HashSet<Race>();
        }
    
        public int Id { get; set; }
        public short Name { get; set; }
        public Nullable<int> RaceCourseID { get; set; }
        public string JP_Distance_Category { get; set; }
    
        public virtual ICollection<Race> Race { get; set; }
    }
}
