//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDayDisplayApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horse
    {
        public Horse()
        {
            this.HorseOdd = new HashSet<HorseOdd>();
            this.Runner = new HashSet<Runner>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string HorseCode { get; set; }
        public string Name { get; set; }
        public string PreviousName { get; set; }
        public Nullable<int> CountryOfOriginId { get; set; }
        public string HK_ChineseName { get; set; }
        public string HK_BrandNumber { get; set; }
        public Nullable<bool> SG_hasBled { get; set; }
        public Nullable<int> SexId { get; set; }
        public Nullable<int> CoatColorId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<short> Z_MaxHcpRating { get; set; }
        public Nullable<short> Z_CurrentHcpRating { get; set; }
        public Nullable<short> Z_StartSeasonHcpRating { get; set; }
    
        public virtual CoatColor CoatColor { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<HorseOdd> HorseOdd { get; set; }
        public virtual Sex Sex { get; set; }
        public virtual ICollection<Runner> Runner { get; set; }
    }
}
