//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDayDisplayApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorseOdd
    {
        public int Id { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<System.DateTime> CurrentTime { get; set; }
        public Nullable<int> HorseNumber { get; set; }
        public Nullable<int> HorseId { get; set; }
        public Nullable<decimal> WinOdds { get; set; }
        public Nullable<decimal> PlaceOdds { get; set; }
    
        public virtual Horse Horse { get; set; }
        public virtual Race Race { get; set; }
    }
}
