//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDayDisplayApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jockey
    {
        public Jockey()
        {
            this.Runner = new HashSet<Runner>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string Fullname { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> isApprentice { get; set; }
        public Nullable<int> CountryOfOriginId { get; set; }
        public Nullable<int> CountryOfRegistrationId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual ICollection<Runner> Runner { get; set; }
    }
}
