//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDayDisplayApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public Meeting()
        {
            this.Race = new HashSet<Race>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CountryId { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public Nullable<int> RaceCourseId { get; set; }
        public Nullable<int> WeatherId { get; set; }
        public Nullable<int> DefaultGoingId { get; set; }
        public Nullable<int> NumberOfRaces { get; set; }
        public Nullable<bool> HK_isNightMeet { get; set; }
        public Nullable<int> CourseVariantId { get; set; }
        public string Z_MeetingCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual CourseVariant CourseVariant { get; set; }
        public virtual Going Going { get; set; }
        public virtual RaceCourse RaceCourse { get; set; }
        public virtual Weather Weather { get; set; }
        public virtual ICollection<Race> Race { get; set; }
    }
}
