//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDayDisplayApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public Race()
        {
            this.HorseOdd = new HashSet<HorseOdd>();
            this.Runner = new HashSet<Runner>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MeetingId { get; set; }
        public Nullable<short> RaceNumber { get; set; }
        public string RaceName { get; set; }
        public Nullable<int> RaceTypeId { get; set; }
        public Nullable<int> DistanceId { get; set; }
        public Nullable<System.DateTime> RaceJumpTimeLocal { get; set; }
        public Nullable<int> HK_RaceIndex { get; set; }
        public Nullable<System.TimeSpan> RaceWinningTime { get; set; }
        public Nullable<int> RaceGoingId { get; set; }
        public Nullable<bool> isTurf { get; set; }
        public Nullable<short> NumberOfRunners { get; set; }
    
        public virtual Distance Distance { get; set; }
        public virtual Going Going { get; set; }
        public virtual ICollection<HorseOdd> HorseOdd { get; set; }
        public virtual Meeting Meeting { get; set; }
        public virtual RaceType RaceType { get; set; }
        public virtual ICollection<Runner> Runner { get; set; }
    }
}
