//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDayDisplayApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CoatColor> CoatColor { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<CourseVariant> CourseVariant { get; set; }
        public DbSet<Distance> Distance { get; set; }
        public DbSet<Gear> Gear { get; set; }
        public DbSet<Going> Going { get; set; }
        public DbSet<Horse> Horse { get; set; }
        public DbSet<HorseOdd> HorseOdd { get; set; }
        public DbSet<Jockey> Jockey { get; set; }
        public DbSet<Language> Language { get; set; }
        public DbSet<Meeting> Meeting { get; set; }
        public DbSet<Race> Race { get; set; }
        public DbSet<RaceCity> RaceCity { get; set; }
        public DbSet<RaceCourse> RaceCourse { get; set; }
        public DbSet<RaceType> RaceType { get; set; }
        public DbSet<Runner> Runner { get; set; }
        public DbSet<Settings> Settings { get; set; }
        public DbSet<Sex> Sex { get; set; }
        public DbSet<Trainer> Trainer { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Weather> Weather { get; set; }
    }
}
