//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDayDisplayApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceCourse
    {
        public RaceCourse()
        {
            this.CourseVariant = new HashSet<CourseVariant>();
            this.Meeting = new HashSet<Meeting>();
            this.Trainer = new HashSet<Trainer>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NameVariant { get; set; }
        public string AUS_Grade { get; set; }
        public string AUS_State { get; set; }
        public Nullable<int> AUS_RaceCityId { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<CourseVariant> CourseVariant { get; set; }
        public virtual ICollection<Meeting> Meeting { get; set; }
        public virtual RaceCity RaceCity { get; set; }
        public virtual ICollection<Trainer> Trainer { get; set; }
    }
}
